### ISSUE TITLE
Incorrect placed button

### ISSUE THREAD

**Issue by kozimov786** [oybek94/namanganliklar24#1]
Current state:
![btn](https://user-images.githubusercontent.com/79497700/111486693-85b4f480-8759-11eb-8768-fa212764c1f6.png)
Expected state:
![btn2](https://user-images.githubusercontent.com/79497700/111486801-9bc2b500-8759-11eb-84f0-20f08cdb0e43.png)

**Comment by oybek94** [comment]
corrected
